apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
  namespace: games
  labels:
    app: game-2048
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: game-2048
